# Generated by Django 4.0.6 on 2022-09-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='tittle',
            new_name='title',
        ),
    ]
