# Generated by Django 4.0.6 on 2022-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_rename_tittle_expediente_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='date',
        ),
        migrations.AddField(
            model_name='expediente',
            name='asignTo',
            field=models.CharField(default=' ', max_length=101),
        ),
        migrations.AddField(
            model_name='expediente',
            name='contratist',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='expediente',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='expediente',
            name='stage',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='expediente',
            name='state',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='creator',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
