# Generated by Django 4.0.6 on 2022-09-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_remove_expediente_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='11-09-2022'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='11-09-2022'),
        ),
    ]
