# Generated by Django 4.0.6 on 2022-09-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expediente',
            new_name='documents',
        ),
    ]
