# Generated by Django 4.0.6 on 2022-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
