# Generated by Django 4.0.6 on 2022-08-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.TextField(null=True),
        ),
    ]
