# Generated by Django 4.0.6 on 2022-08-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
